# Generated by Django 4.2.2 on 2023-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_urun_kategori_kullanici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
