# Generated by Django 4.2.2 on 2023-07-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_kullanici_customer_alter_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='odemepay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='odemepay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='odemepay_payment_status',
            new_name='razorpay_payment_status',
        ),
    ]
