# Generated by Django 4.2.2 on 2023-07-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='product',
            new_name='urun',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='urun',
        ),
    ]
