# Generated by Django 4.2.2 on 2023-07-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_product_orderplaced_urun_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='urun',
            new_name='urunn',
        ),
    ]
