# Generated by Django 4.2.2 on 2023-07-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_urun_wishlist_urunn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='urunn',
            new_name='urun',
        ),
    ]
